name: Build the builder
permissions:
  contents: read
  packages: write
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile.builder'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/builder.yml'
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
    #       actions/checkout@v2
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
    #       docker/build-push-action@v1
    - uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991
      with:
        dockerfile: Dockerfile.builder
        tags: latest
        tag_with_sha: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: microsoft/opensource.microsoft.com/custom-jekyll-builder
